### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/styled-system#82]
The following items need to be written up as issues and tagged with the v2 milestone.

- [x] convert to ES module syntax
- [x] remove idx
- [x] remove legacy responsiveStyle args parsing
- [x] consolidate style functions into single file
- [x] consolidate low-level utilities into single file
- [x] deprecate remove-props
- [x] use verbose names for flex properties
- [x] Numbers in `breakpoints` should convert to pixels
- [x] update default theme #91
- [x] add accessor argument to low-level utilities #87 #50
- [x] Ensure style prop names are unique #89 
- [x] Add alias option to low-level utilities #90
- [x] Remove `boolValue` option & boolean props
- [x] Normalize border utilities api #98
- [x] subpackages for monorepo
  - [x] clean-element
  - [x] clean-tag
  - [x] system-components
- [x] rename theme getter util #88
- [ ] update readme docs

**For consideration** these can be handled as separate non-breaking changes
- compose function for space & color
- props combinations utility
- add support for verbose margin and padding props
- [x] ~~add more docs w/ live examples~~ (not a breaking change and can be a follow-up task)
